### ISSUE TITLE
Readme descriptor of the repository

### ISSUE THREAD

**Issue by grahamjamesr7** [MichaelJGarlotteII/testProject#8]
I think it would be a good idea for us to have a detailed readme that's a basically a mirror of the About This Site page, so that visitors to the repository can get an understanding of what the site is and how it works without having to visit the site itself. You never know where a visitor will arrive from -- they could stumble across this repo directly from github, with no understanding of the website in the wild!

**Comment by MichaelJGarlotteII** [comment]
README is complete and has been added to the about-pages feature branch. This will merge to develop when I complete the about.html page.
